### ISSUE TITLE
Feature request: Add "FPS Limit" option to the settings menu

### ISSUE THREAD

**Issue by Frizy13** [pastthepixels/InfiniteShooter#1]
**Is your feature request related to a problem? Please describe.**
I think the frame limit is an important option because it allows you to remove unnecessary load from the GPU. For example, it makes no sense to play at 200 fps if your monitor only allows 60.

**Describe the solution you'd like**
You can add an additional option to the "Graphics" section of the settings.

**Describe alternatives you've considered**
Unfortunately, I haven't come up with an alternative.

**If possible, provide any screenshots or mockups of your intended feature**
![image](https://user-images.githubusercontent.com/92388250/177618846-7582eed1-483b-427a-a4ed-fdfe82a7f7a0.png)

**Additional context**

**Comment by Frizy13** [comment]
It looks like such a feature is already in the engine. As the documentation says, "To change the number of iterations of physics during runtime, use Engine.iterations_per_second". If this is not what you need, please correct me.

**Comment by pastthepixels** [comment]
Yeah, I looked it up and it is indeed already a thing. I was probably thinking of [physics interpolation](https://docs.godotengine.org/en/3.5/tutorials/physics/interpolation/index.html), which should help to make things look less janky should the physics engine refresh at a slower rate than things are drawn. But although a separate settings to cap the FPS of the physics engine can be added now, I miiiiight just be lazy and use this as an excuse not to add a separate FPS cap for the physics engine until Godot 3.5...

**Comment by pastthepixels** [comment]
Just merged some code for this with branch 0.4.0! (Well, actually, that was a couple of hours ago...) Anyway, it's set for InfiniteShooter 0.4.1!
